### PR TITLE
67: Refactor landing page routes

### LINKED ISSUE #67: Refactor landing page routes
- Path
  - RSS Data Source - `/listen?uf={RSS ULR}[&ge={EPISODE GUI}` /listen/index.tsx
  - API Data Source - `/listen/{SERIES GUID}[/{EPISODE GUID}` - /listen/[...params].tsx
- Update landing page data parser

### PR DESCRIPTION
**Pull request by rpeterman-gp**
Closes #67

- Updates listen page data parser to include all data need to for new layout
- Updates listen page to render placeholder content using the parsed data
- Reorganizes interface directories and updates imports

## To Review

- [x] Checkout Branch.
- [x] Run `asdf install`.
- [x] Run `yarn`.
- [x] Run `yarn dev`.

> ...then...

- [x] Go to http://localhost:4300/listen?uf=http://feed.songexploder.net/SongExploder
- [x] Ensure page renders with data from feed
- [x] Go to http://localhost:4300/listen?uf=http://feed.songexploder.net/SongExploder&ge=prx_93_997e0366-7085-4789-a578-7c7821f7e992
- [x] Ensure page renders with data for that episode
- [x] Try it with your favorite feeds. `uf=[FEED URL]` and/or `ge=[EPISODE GUID]`

> NOTE: The ability to navigate to and from episodes in the UI will come in later PR.

### CODE REVIEW

**Comment by brandonhundt** [comment]
@rpeterman-gp A couple of issues:

1. When I go to the Song Exploder Episode GUID, I don't see any content changes:

Screen Shot 2022-07-27 at 1 44 40 PM

2. When I go to TW's feed http://localhost:4300/listen?uf=https://feeder.prx.org/podcasts/300 or to an episode: http://localhost:4300/listen?uf=https://feeder.prx.org/podcasts/300&ge=prx_300_f2c6471b-914b-4715-81a6-18222341d394 I get an error:

Screen Shot 2022-07-27 at 1 43 07 PM

**Review by brandonhundt — CHANGES_REQUESTED** [review]
See previous comment ^ 

(This comment is intended to stop Angry Pull Requests from yelling at me)

**Comment by rpeterman-gp** [comment]
@brandonhundt Ok. That should be fixed now.

**Review by brandonhundt — APPROVED** [review]
@rpeterman-gp working now. :shipit:

**Pull request merged**
